Information:
  project: PR105

InputData:
  DIDDataExcel: DIDData_PR105.xlsx
  DIDStatusExcel: DIDStatus_PR105.xlsx
  DiagSeqExcel: Diagnostic_sequences.xlsx
  PathToArxml: ../PR105/TBMU_MAIN/App/Tresos_TBMU_App/output/generated/output/ConfigFull.arxml
  PathToMergedArxml: MergedFiles.arxml

CanConfig:
  TxId: 0x6B4
  RxId: 0x694
  IsCanFD: False
  IsExtended: False
  IsFiltered: True
  IsPadded: False
  timeout: 3
  PcanLib: CanApi4Lib
  # PcanLib: PCANBasicLib
  PCANBasicConfig:
    PcanHandle: PCAN_USBBUS1
    Bitrate: PCAN_BAUD_500K
    BitrateFD: f_clock_mhz=20, nom_brp=5, nom_tseg1=2, nom_tseg2=1, nom_sjw=1, data_brp=2, data_tseg1=3, data_tseg2=1, data_sjw=1
  CanApi4Config:
    device: pcan_usb
    client_name: PythonClient
    net_name: Can_500k

Options:
  PDX_options:
    PDX_Folder: To_Program/PDX/
  ULP_Options:
    ULP_Folder: To_Program/ULP/
