project: PR128
DIDStatusCsv: DIDStatus_PR128.csv
DIDStatusExcel: DIDStatus_PR128.xlsx
PathToDextSupplierArxml: ../BmsGen2/Inputs/DEXT/E401800_V8_supplier.arxml
PathToDextAppliArxml: ../BmsGen2/Inputs/DEXT/E401800_V8_noMappingSupplier.arxml
pathToAssemblyConnectionDID: ../BmsGen2_Copy/Inputs/DEXT/Dext_Connections.arxml
CanConfig:
  TxId: 0x18DADBF1
  RxId: 0x18DAF1DB
  IsCanFD: True
  IsExtended: True
  IsFiltered: True
  IsPadded: True
  timeout: 10
  PcanLib: CanApi4Lib
  # PcanLib: PCANBasicLib
  PCANBasicConfig:
    PcanHandle: PCAN_USBBUS1
    Bitrate: PCAN_BAUD_500K
    BitrateFD: f_clock_mhz=20, nom_brp=1, nom_tseg1=31, nom_tseg2=8, nom_sjw=8, data_brp=1, data_tseg1=6, data_tseg2=3, data_sjw=3
  CanApi4Config:
    device: pcan_usb
    client_name: PythonClient
    net_name: CANFD_ETS
