project: PR128
DIDStatusCsv: DIDStatus_PR128.csv
DIDStatusExcel: DIDStatus_PR128.xlsx
PathToDextArxml: ../BmsGen2/Inputs/DEXT/BMS_AW010700.arxml
pathToAssemblyConnectionDID: ../BmsGen2/Inputs/DEXT/Dext_Connections.arxml
CanConfig:
  TxId: 0x18DADBF1
  RxId: 0x18DAF1DB
  IsCanFD: False
  IsExtended: True
  IsFiltered: True
  IsPadded: True
  timeout: 10
  PcanLib: CanApi4Lib
  # PcanLib: PCANBasicLib
  PCANBasicConfig:
    PcanHandle: PCAN_USBBUS1
    Bitrate: PCAN_BAUD_500K
  CanApi4Config:
    device: pcan_usb
    client_name: PythonClient
    net_name: ch1_500kb
