Information:
  project: PR128

InputData:
  DIDDataExcel: DIDData_PR128.xlsx
  DIDStatusExcel: DIDStatus_PR128.xlsx
  # PathToArxml: ../PR128/BmsGen2/Inputs/DEXT/E401800_V8_noMappingSupplier.arxml
  PathToArxmlList:
    - ../PR128/BmsGen2_Master/Software/Config/RtaCar/ecu_config/bsw/Dcm_SWC.arxml
    - ../PR128/BmsGen2_Master/Software/Config/RtaCar/ecu_config/bsw/Dem_SWC.arxml
    - ../PR128/BmsGen2_Master/Software/Config/RtaCar/ecu_config/bsw/Dcm_EcucValues_Static.arxml
    - ../PR128/BmsGen2_Master/Software/Config/RtaCar/ecu_config/bsw/Dem_EcucValues_Static.arxml
    - ../PR128/BmsGen2_Master/Software/Config/RtaCar/ecu_config/bsw/Fim_EcucValues_Static.arxml
    - ../PR128/BmsGen2_Master/Software/Config/RtaCar/ecu_config/bsw/HV_BMS_Project_Dcm_EcucValues.arxml
    - ../PR128/BmsGen2_Master/Software/Config/RtaCar/ecu_config/bsw/HV_BMS_Project_Dem_EcucValues.arxml
    - ../PR128/BmsGen2_Master/Software/Config/RtaCar/ecu_config/bsw/HV_BMS_Project_FiM_EcucValues.arxml
  
CanConfig:
  TxId: 0x18DADBF1
  RxId: 0x18DAF1DB
  IsCanFD: True
  IsExtended: True
  IsFiltered: True
  IsPadded: True
  timeout: 10
  PcanLib: CanApi4Lib
  # PcanLib: PCANBasicLib
  PCANBasicConfig:
    PcanHandle: PCAN_USBBUS1
    Bitrate: PCAN_BAUD_500K
    BitrateFD: f_clock_mhz=20, nom_brp=1, nom_tseg1=31, nom_tseg2=8, nom_sjw=8, data_brp=1, data_tseg1=6, data_tseg2=3, data_sjw=3
  CanApi4Config:
    device: pcan_usb
    client_name: PythonClient
    net_name: CANFD_ETS

Options:
  PDX_options:
    PDX_Folder: To_Program/PDX/
  ULP_Options:
    ULP_Folder: To_Program/ULP/
