project: PR128
DIDDataExcel: DIDData_PR128.xlsx
DIDStatusExcel: DIDStatus_PR128.xlsx
PathToArxml: ../PR128/BmsGen2/Inputs/DEXT/E401800_V8_noMappingSupplier.arxml
CanConfig:
  TxId: 0x18DADBF1
  RxId: 0x18DAF1DB
  IsCanFD: True
  IsExtended: True
  IsFiltered: True
  IsPadded: True
  timeout: 10
  PcanLib: CanApi4Lib
  # PcanLib: PCANBasicLib
  PCANBasicConfig:
    PcanHandle: PCAN_USBBUS1
    Bitrate: PCAN_BAUD_500K
    BitrateFD: f_clock_mhz=20, nom_brp=1, nom_tseg1=31, nom_tseg2=8, nom_sjw=8, data_brp=1, data_tseg1=6, data_tseg2=3, data_sjw=3
  CanApi4Config:
    device: pcan_usb
    client_name: PythonClient
    net_name: CANFD_ETS
